# -*- coding: utf-8 -*-
"""speech_commands.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9inCogIYI1V_kbWiWvwpIk7-7xWPsXL
"""

import pathlib
import tensorflow as tf
import random
import numpy as np
import subprocess

subprocess.run(["rm", "-rf", "data/speech_commands_v0.02"])
subprocess.run(["mkdir", "-p", "data/speech_commands_v0.02"])
subprocess.run(["wget", "-c", "https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz", "-P", "data/speech_commands_v0.02"])
subprocess.run(["tar", "-tzf", "data/speech_commands_v0.02/speech_commands_v0.02.tar.gz", ">", "/dev/null", "&&", "echo", "archive OK"])
subprocess.run(["tar", "-xzf", "data/speech_commands_v0.02/speech_commands_v0.02.tar.gz", "-C", "data/speech_commands_v0.02"])

DATA_URL = "https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz"
data_dir = pathlib.Path("data/speech_commands_v0.02")

if not data_dir.exists():
    tf.keras.utils.get_file(
        fname="speech_commands_v0.02.tar.gz",
        origin=DATA_URL,
        extract=True,
        cache_dir=".",
        cache_subdir="data/speech_commands_v0.02",
    )

words = sorted(p.name for p in data_dir.iterdir() if p.is_dir() and not p.name.startswith("_"))
print(f"{len(words)} word folders:", words)
assert (data_dir / "validation_list.txt").exists()
assert (data_dir / "testing_list.txt").exists()
assert (data_dir / "_background_noise_").exists()

def extract_mfcc(waveform):  # waveform: 16000 float32 samples in [-1, 1]
    stft = tf.signal.stft(
        waveform,
        frame_length=640,   # 40ms * 16kHz
        frame_step=320,     # 20ms * 16kHz
        fft_length=1024,
    )
    spectrogram = tf.abs(stft)

    mel_weight_matrix = tf.signal.linear_to_mel_weight_matrix(
        num_mel_bins=40,           # ARM's recipe computes 40 mel bins, then DCTs down to 10
        num_spectrogram_bins=stft.shape[-1],
        sample_rate=16000,
        lower_edge_hertz=20.0,
        upper_edge_hertz=4000.0,
    )
    mel_spectrogram = tf.matmul(spectrogram, mel_weight_matrix)
    log_mel = tf.math.log(mel_spectrogram + 1e-6)

    mfcc = tf.signal.mfccs_from_log_mel_spectrograms(log_mel)
    return mfcc[..., :10]   # keep first 10 cepstral coefficients

DATA_DIR = pathlib.Path("data/speech_commands_v0.02")
TARGET_WORDS = ["yes", "no", "up", "down", "left", "right", "on", "off", "stop", "go"]

def load_split_sets():
    val_set = set((DATA_DIR / "validation_list.txt").read_text().splitlines())
    test_set = set((DATA_DIR / "testing_list.txt").read_text().splitlines())
    return val_set, test_set

def gather_word_files():
    val_set, test_set = load_split_sets()
    splits = {"train": [], "val": [], "test": []}
    for word_dir in sorted(DATA_DIR.iterdir()):
        word = word_dir.name
        if not word_dir.is_dir() or word == "_background_noise_":
            continue
        label = word if word in TARGET_WORDS else "unknown"
        for wav_path in word_dir.glob("*.wav"):
            rel = f"{word}/{wav_path.name}"
            entry = (str(wav_path), label)
            bucket = "val" if rel in val_set else "test" if rel in test_set else "train"
            splits[bucket].append(entry)
    return splits

def time_shift(waveform, max_shift_samples=1600):
    length = tf.shape(waveform)[0]
    shift = tf.random.uniform([], -max_shift_samples, max_shift_samples + 1, dtype=tf.int32)

    pad_start = tf.maximum(shift, 0)
    pad_end = tf.maximum(-shift, 0)
    padded = tf.pad(waveform, [[pad_start, pad_end]])

    offset = tf.maximum(-shift, 0)
    return padded[offset:offset + length]

def mix_in_background_noise(waveform, noise_pool, background_frequency=0.8, max_background_volume=0.1):
    apply_noise = tf.cast(tf.random.uniform([]) < background_frequency, tf.float32)
    volume = tf.random.uniform([], 0.0, max_background_volume) * apply_noise

    idx = tf.random.uniform([], 0, tf.shape(noise_pool)[0], dtype=tf.int32)
    noise_segment = noise_pool[idx]

    mixed = waveform + volume * noise_segment
    return tf.clip_by_value(mixed, -1.0, 1.0)


def build_noise_segment_pool(background_clips, num_segments=200, segment_len=16000):
    pool = []
    for _ in range(num_segments):
        clip = background_clips[random.randrange(len(background_clips))]
        start = random.randrange(0, len(clip) - segment_len)
        pool.append(clip[start:start + segment_len])
    return tf.constant(np.stack(pool), dtype=tf.float32)  # shape (num_segments, 16000)

def balance_unknown(entries, target_count_per_split):
    words = [e for e in entries if e[1] != "unknown"]
    unknown = [e for e in entries if e[1] == "unknown"]
    random.shuffle(unknown)
    return words + unknown[:target_count_per_split]

def load_background_clips():
    bg_dir = DATA_DIR / "_background_noise_"
    clips = []
    for wav_path in bg_dir.glob("*.wav"):
        audio = tf.audio.decode_wav(tf.io.read_file(str(wav_path)), desired_channels=1).audio
        clips.append(tf.squeeze(audio, axis=-1).numpy())  # 1D float32 array
    return clips

def make_silence_waveforms(clips, count):
    out = []
    for _ in range(count):
        clip = clips[random.randrange(len(clips))]
        start = random.randrange(0, len(clip) - 16000)
        out.append(clip[start:start + 16000])
    return out

def waveform_from_path(path, label_id):
    audio = tf.audio.decode_wav(tf.io.read_file(path), desired_channels=1, desired_samples=16000).audio
    return tf.squeeze(audio, axis=-1), label_id

def augment_waveform(waveform, label_id, noise_pool):
    waveform = time_shift(waveform)
    waveform = mix_in_background_noise(waveform, noise_pool)
    return waveform, label_id

def build_dataset(word_entries, silence_waveforms, label_to_id, training):
    paths = [p for p, _ in word_entries]
    label_ids = [label_to_id[l] for _, l in word_entries]
    word_ds = tf.data.Dataset.from_tensor_slices((paths, label_ids)).map(
        waveform_from_path, num_parallel_calls=tf.data.AUTOTUNE
    )

    silence_ids = tf.fill([len(silence_waveforms)], label_to_id["silence"])
    silence_ds = tf.data.Dataset.from_tensor_slices(
        (tf.stack(silence_waveforms), silence_ids)
    )

    ds = word_ds.concatenate(silence_ds)
    noise_pool = build_noise_segment_pool(bg_clips)
    if training:
        ds = ds.map(lambda wav, lbl: augment_waveform(wav, lbl, noise_pool),
                  num_parallel_calls=tf.data.AUTOTUNE)
        ds = ds.shuffle(4096)

    ds = ds.map(
        lambda wav, lbl: (extract_mfcc(wav), lbl),
        num_parallel_calls=tf.data.AUTOTUNE,
    )
    ds = ds.map(lambda mfcc, lbl: (tf.expand_dims(mfcc, -1), lbl))  # add channel dim -> (49,10,1)
    return ds.batch(100).prefetch(tf.data.AUTOTUNE)

splits = gather_word_files()
label_to_id = {w: i for i, w in enumerate(TARGET_WORDS + ["unknown", "silence"])}

bg_clips = load_background_clips()

def target_class_count(entries):
      """Average number of examples in a single target-word class, for this split."""
      words = [e for e in entries if e[1] != "unknown"]
      return len(words) // len(TARGET_WORDS)

train_target_count = target_class_count(splits["train"])
val_target_count = target_class_count(splits["val"])
test_target_count = target_class_count(splits["test"])

train_entries = balance_unknown(splits["train"], target_count_per_split=train_target_count)
val_entries = balance_unknown(splits["val"], target_count_per_split=val_target_count)
test_entries = balance_unknown(splits["test"], target_count_per_split=test_target_count)

train_ds = build_dataset(train_entries, make_silence_waveforms(bg_clips, train_target_count), label_to_id, training=True)
val_ds = build_dataset(val_entries, make_silence_waveforms(bg_clips, val_target_count), label_to_id, training=False)
test_ds = build_dataset(test_entries, make_silence_waveforms(bg_clips, test_target_count), label_to_id, training=False)

val_silence = make_silence_waveforms(bg_clips, val_target_count)

def build_ds_cnn_s(num_classes=12):
    inputs = tf.keras.Input(shape=(49, 10, 1))

    x = tf.keras.layers.Conv2D(64, (10, 4), strides=(2, 2), padding="same")(inputs)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.ReLU()(x)

    for _ in range(4):
        x = tf.keras.layers.DepthwiseConv2D((3, 3), strides=(1, 1), padding="same")(x)
        x = tf.keras.layers.BatchNormalization()(x)
        x = tf.keras.layers.ReLU()(x)
        x = tf.keras.layers.Conv2D(64, (1, 1), padding="same")(x)
        x = tf.keras.layers.BatchNormalization()(x)
        x = tf.keras.layers.ReLU()(x)

    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)
    return tf.keras.Model(inputs, outputs)

model = build_ds_cnn_s()
lr_schedule = tf.keras.optimizers.schedules.PiecewiseConstantDecay(
    boundaries=[10000, 20000],
    values=[5e-4, 1e-4, 2e-5],
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

checkpoint_path = "ml/training/checkpoints/ds_cnn_s.weights.h5"
checkpoint_cb = tf.keras.callbacks.ModelCheckpoint(
    checkpoint_path,
    monitor="val_accuracy",
    save_best_only=True,
    save_weights_only=True,
)

model.fit(train_ds, validation_data=val_ds, epochs=100, callbacks=[checkpoint_cb])
model.load_weights(checkpoint_path)

def build_calibration_dataset(entries, silence_waveforms, label_to_id, num_samples=300):
    paths = [p for p, _ in entries]
    label_ids = [label_to_id[l] for _, l in entries]
    word_ds = tf.data.Dataset.from_tensor_slices((paths, label_ids)).map(
        waveform_from_path, num_parallel_calls=tf.data.AUTOTUNE
    )

    silence_ids = tf.fill([len(silence_waveforms)], label_to_id["silence"])
    silence_ds = tf.data.Dataset.from_tensor_slices((tf.stack(silence_waveforms), silence_ids))

    ds = word_ds.concatenate(silence_ds)
    return ds.shuffle(2000, seed=42).take(num_samples)

def representative_dataset():
    calibration_ds = build_calibration_dataset(val_entries, val_silence, label_to_id, num_samples=300)

    for waveform, _ in calibration_ds:
        mfcc = extract_mfcc(waveform)
        mfcc = tf.expand_dims(mfcc, -1)  # add channel dim -> (49, 10, 1)
        mfcc = tf.expand_dims(mfcc, 0)   # add batch dim  -> (1, 49, 10, 1)
        yield [mfcc]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
tflite_model = converter.convert()

with open("ds_cnn_s.tflite", "wb") as f:
    f.write(tflite_model)

test_loss, test_acc = model.evaluate(test_ds)
print(f"Float model test accuracy: {test_acc:.4f}")

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()[0]
output_details = interpreter.get_output_details()[0]
input_scale, input_zero_point = input_details["quantization"]

correct = 0
total = 0

for mfcc_batch, label_batch in test_ds:
    for mfcc, label in zip(mfcc_batch, label_batch):
        quantized_input = tf.round(mfcc / input_scale + input_zero_point)
        quantized_input = tf.clip_by_value(quantized_input, -128, 127)
        quantized_input = tf.cast(quantized_input, input_details["dtype"])
        quantized_input = tf.expand_dims(quantized_input, 0)  # add batch dim -> (1,49,10,1)

        interpreter.set_tensor(input_details["index"], quantized_input)
        interpreter.invoke()
        output = interpreter.get_tensor(output_details["index"])[0]

        predicted_label = tf.argmax(output).numpy()
        correct += int(predicted_label == label.numpy())
        total += 1

quantized_accuracy = correct / total
print(f"Quantized model test accuracy: {quantized_accuracy:.4f}")
